/**
 * Shared domain types for Nurture's data/auth/sync/privacy layer.
 *
 * These types describe the offline-first journal model: events are the
 * timeline source of truth, stored locally in SQLite and mirrored to
 * Supabase when configured. No secrets live in this file.
 */

export type EventType =
  | 'note'
  | 'mood'
  | 'symptom'
  | 'weight'
  | 'photo'
  | 'appointment'
  | 'kick_session'
  | 'milestone'
  | 'question'
  | 'file'
  | (string & {});

export type Visibility = 'private' | 'shared' | 'export';

/** Input for creating a journal event. IDs and timestamps are generated by the store. */
export interface EventInput {
  userId?: string | null;
  pregnancyId?: string | null;
  type: EventType;
  occurredAt?: string; // ISO 8601; defaults to now
  visibility?: Visibility; // defaults to 'private'
  /** Arbitrary payload (text, mood value, symptom list, media references, ...). */
  data?: Record<string, unknown>;
  /** Media seam (later epic): photo/file bytes are NOT uploaded here. data may
   *  carry local URIs/storage paths; a media-upload step will attach bytes later. */
}

/** A journal event as stored locally (SQLite) and mirrored to Supabase. */
export interface LocalEvent {
  id: string; // uuid v4, primary key
  userId: string | null;
  pregnancyId: string | null;
  type: EventType;
  occurredAt: string; // ISO 8601
  visibility: Visibility;
  data: Record<string, unknown>;
  /** Client-generated idempotency key; the server upserts on this to avoid dupes. */
  idempotencyKey: string;
  /** Tombstone: set when deleted. Row is kept until the server acknowledges it. */
  deletedAt: string | null; // ISO 8601
  updatedAt: string; // ISO 8601
  /** True while the row has local changes not yet pushed to the server. */
  dirty: boolean;
}

/** A pregnancy record (local mirror of the server's pregnancies table). */
export interface Pregnancy {
  id: string;
  userId: string | null;
  dueDate: string | null; // YYYY-MM-DD
  lmpDate: string | null; // YYYY-MM-DD
  pregnancyType: 'singleton' | 'multiples';
  parity: 'first' | 'subsequent';
  status: 'active' | 'stopped';
  updatedAt: string; // ISO 8601
  dirty: boolean;
}

/** Notification preferences (v1 set). Stored locally; mirrored to the server when configured. */
export interface Prefs {
  endOfDayEnabled: boolean;
  endOfDayTime: string; // 'HH:MM', e.g. '20:30'
  quietHoursStart: string; // 'HH:MM'
  quietHoursEnd: string; // 'HH:MM'
  appointmentReminders: boolean;
  appointmentLeadMinutes: number; // minutes before an appointment, default 60
  globalPauseUntil: string | null; // ISO 8601
}

/** A sync conflict: local edits and a newer server version that must NOT be silently merged. */
export interface SyncConflict<TLocal = LocalEvent | Pregnancy> {
  id: string; // event or pregnancy id
  /** Which table the conflicted row belongs to. */
  kind: 'event' | 'pregnancy';
  local: TLocal;
  remote: TLocal;
  detectedAt: string; // ISO 8601
}
