/**
 * Shared domain types for Nurture's data/auth/sync/privacy layer.
 *
 * These types describe the offline-first journal model: events are the
 * timeline source of truth, stored locally in SQLite and mirrored to
 * Supabase when configured. No secrets live in this file.
 */

export type EventType =
  | 'note'
  | 'mood'
  | 'symptom'
  | 'weight'
  | 'photo'
  | 'appointment'
  | 'kick_session'
  | 'milestone'
  | 'question'
  | 'file'
  | (string & {});

export type Visibility = 'private' | 'shared' | 'export';

/**
 * One photo/file attached to an event (Epic 2.3 shape).
 *
 * `local_uri` is device-only (file:// on native, blob: on web) and is never
 * sent to the server as-is. `upload` tracks cloud backup: 'pending' = bytes
 * still on this device, 'done' = bytes in her private storage bucket,
 * 'failed' = last attempt failed (honest "not backed up" state; retries
 * continue in the background).
 */
export interface EventAttachment {
  id: string;
  kind: 'photo' | 'file';
  name: string;
  mimeType?: string;
  size?: number; // bytes, best-effort
  /** Device-local URI. Never leaves the device via sync. */
  local_uri?: string;
  upload: 'pending' | 'done' | 'failed';
  /** Cloud object path once uploaded: {user_id}/{event_id}/{attachment_id}.{ext} */
  storage_path?: string;
}

/** Which private bucket an attachment kind lives in. */
export function bucketForKind(kind: EventAttachment['kind']): 'photos' | 'files' {
  return kind === 'photo' ? 'photos' : 'files';
}

/** Input for creating a journal event. IDs and timestamps are generated by the store. */
export interface EventInput {
  userId?: string | null;
  pregnancyId?: string | null;
  type: EventType;
  occurredAt?: string; // ISO 8601; defaults to now
  visibility?: Visibility; // defaults to 'private'
  /** Arbitrary payload (text, mood value, symptom list, media references, ...). */
  data?: Record<string, unknown>;
  /**
   * Media seam (Epic 2.3, built): photo/file bytes upload through the media
   * outbox (src/sync/media.ts) into her private storage buckets. `data` may
   * carry EventAttachment entries (local_uri + upload status + storage_path);
   * text/data saves never wait for media uploads.
   */
}

/** A journal event as stored locally (SQLite) and mirrored to Supabase. */
export interface LocalEvent {
  id: string; // uuid v4, primary key
  userId: string | null;
  pregnancyId: string | null;
  type: EventType;
  occurredAt: string; // ISO 8601
  visibility: Visibility;
  data: Record<string, unknown>;
  /** Client-generated idempotency key; the server upserts on this to avoid dupes. */
  idempotencyKey: string;
  /** Tombstone: set when deleted. Row is kept until the server acknowledges it. */
  deletedAt: string | null; // ISO 8601
  updatedAt: string; // ISO 8601
  /** True while the row has local changes not yet pushed to the server. */
  dirty: boolean;
}

/** A pregnancy record (local mirror of the server's pregnancies table). */
export interface Pregnancy {
  id: string;
  userId: string | null;
  dueDate: string | null; // YYYY-MM-DD
  lmpDate: string | null; // YYYY-MM-DD
  pregnancyType: 'singleton' | 'multiples';
  parity: 'first' | 'subsequent';
  status: 'active' | 'stopped';
  updatedAt: string; // ISO 8601
  dirty: boolean;
}

/** Notification preferences (v1 set). Stored locally; mirrored to the server when configured. */
export interface Prefs {
  endOfDayEnabled: boolean;
  endOfDayTime: string; // 'HH:MM', e.g. '20:30'
  quietHoursStart: string; // 'HH:MM'
  quietHoursEnd: string; // 'HH:MM'
  appointmentReminders: boolean;
  appointmentLeadMinutes: number; // minutes before an appointment, default 60
  globalPauseUntil: string | null; // ISO 8601
}

/** A sync conflict: local edits and a newer server version that must NOT be silently merged. */
export interface SyncConflict<TLocal = LocalEvent | Pregnancy> {
  id: string; // event or pregnancy id
  /** Which table the conflicted row belongs to. */
  kind: 'event' | 'pregnancy';
  local: TLocal;
  remote: TLocal;
  detectedAt: string; // ISO 8601
}

// ─────────────────────────────────────────────────────────────
// Epic 6 — reminders (APPEND-ONLY; other epics add their own marked sections)
// ─────────────────────────────────────────────────────────────

/**
 * State of one "question for the visit" on an appointment event (contract C1).
 *
 * - 'to_ask': she hasn't raised it yet (the default for a new question).
 * - 'asked': she raised it during the visit; no answer captured yet.
 * - 'answered': the provider answered and she (or the note) captured it.
 * - 'deferred': deliberately parked for a later visit.
 * - 'dismissed': dropped — struck through, kept for the record.
 *
 * Stored per question in the appointment event's `data.questions` array
 * (see src/plan/questions.ts for the storage rationale). Other epics are
 * read-only consumers of this type and its storage.
 */
export type QuestionState = 'to_ask' | 'asked' | 'answered' | 'deferred' | 'dismissed';

/* ── Epic 9: changed-outcome mode ── */

/** The owner's decision about her timeline after stopping. */
export type StoryDecision = 'kept' | 'exported' | 'deleted';

/** The owner's decision about previously shared partner memories. */
export type PartnerMemoryDecision = 'kept' | 'removed';

/**
 * The owner's data decisions after stopping (contract C3 aftermath).
 * Absent fields = undecided — "I'll decide later" is first-class, and
 * everything stays private until she chooses.
 */
export interface AftermathDecisions {
  story?: StoryDecision;
  partnerMemories?: PartnerMemoryDecision;
  /** ISO 8601 of the most recent decision. */
  decidedAt?: string;
}

/**
 * One gentle-read entry (Epic 9 "Gentle reads" module).
 * Titles are placeholders for the reviewed content pack — see
 * src/support/gentleReads.ts. Never described as clinician-reviewed.
 */
export interface GentleRead {
  id: string;
  title: string;
  blurb: string;
}
