#!/usr/bin/env python3
"""Merge supabase/functions/pregnancy-chat/{lib,index}.ts into one
self-contained file for Anuraj's paste-deploy of the pregnancy-chat
edge function (like report-summary-single.ts).

Usage: python3 tools/make_pregnancy_chat_single.py
Writes: ~/workspace/your_files/pregnancy-chat-single.ts
"""
import os
import re

REPO = os.path.expanduser("~/workspace/nurture-v12")
LIB = os.path.join(REPO, "supabase/functions/pregnancy-chat/lib.ts")
INDEX = os.path.join(REPO, "supabase/functions/pregnancy-chat/index.ts")
OUT = os.path.expanduser("~/workspace/your_files/pregnancy-chat-single.ts")

with open(LIB) as f:
    lib_src = f.read()
with open(INDEX) as f:
    index_src = f.read()

HEADER = """/**
 * pregnancy-chat — Ask Willow edge function, SELF-CONTAINED deploy file
 * (Anuraj, Sept 20, 2026).
 *
 * Paste this whole file as index.ts when creating the `pregnancy-chat`
 * function in the Supabase dashboard (project nurture), then set the
 * GEMINI_API_KEY secret. See supabase/functions/pregnancy-chat/README.md
 * for the exact steps.
 *
 * Generated from supabase/functions/pregnancy-chat/{lib,index}.ts —
 * do not edit this file directly; edit the sources and regenerate with
 * tools/make_pregnancy_chat_single.py.
 */

"""

# Strip the lib import from index.ts and inline lib.ts in its place.
import_re = re.compile(
    r"import\s*\{[^}]*\}\s*from\s*['\"]\./lib\.ts['\"];?\n", re.MULTILINE
)
m = import_re.search(index_src)
assert m, "lib import not found in index.ts"
merged = HEADER + index_src[: m.start()] + lib_src.rstrip() + "\n\n" + index_src[m.end() :]

# Sanity: no remaining relative imports.
for line in merged.splitlines():
    assert not re.match(r"\s*import .* from '\./", line), f"relative import left: {line}"
assert "handleChatPost" in merged and "Deno.serve" in merged

with open(OUT, "w") as f:
    f.write(merged)
print(f"wrote {OUT} ({len(merged)} bytes)")
